import * as dotenv from 'dotenv';
import Groq from 'groq-sdk';
import { chromium } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

dotenv.config();

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

async function captureScreenshot(url: string, name: string, viewport = { width: 1280, height: 720 }): Promise<string> {
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport });
  const page = await context.newPage();

  await page.goto(url, { timeout: 15000 });
  await page.waitForTimeout(2000); // Let page fully render

  const dir = path.join(process.cwd(), 'visual-regression');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir);

  const screenshotPath = path.join(dir, `${name}.png`);
  await page.screenshot({ path: screenshotPath, fullPage: true });
  await browser.close();

  return screenshotPath;
}

async function analyzeScreenshot(screenshotPath: string, context: string): Promise<string> {
  const imageData = fs.readFileSync(screenshotPath);
  const base64Image = imageData.toString('base64');

  const result = await groq.chat.completions.create({
    model: 'meta-llama/llama-4-scout-17b-16e-instruct',
    messages: [
      {
        role: 'user',
        content: [
          {
            type: 'text',
            text: `You are a UX-focused QA engineer reviewing a screenshot of a booking page.

Context: ${context}

Analyze this screenshot and report on:
1. LAYOUT: Are all key elements visible and properly positioned?
2. CTA VISIBILITY: Is the primary call-to-action (book/select date) clearly visible without scrolling?
3. READABILITY: Is text legible and not overlapping?
4. CONVERSION RISKS: Any visual issues that could prevent a user from completing a booking?
5. OVERALL SCORE: Rate the visual UX quality from 1-10

Be specific. Reference actual elements you can see in the screenshot.`
          },
          {
            type: 'image_url',
            image_url: {
              url: `data:image/png;base64,${base64Image}`
            }
          }
        ]
      }
    ]
  });

  return result.choices[0].message.content!;
}

async function compareViewports(url: string) {
  console.log('\n👁️  AI Visual Regression Analysis');
  console.log('=====================================\n');
  console.log(`URL: ${url}\n`);

  const viewports = [
    { name: 'desktop', width: 1280, height: 720, label: 'Desktop (1280x720)' },
    { name: 'tablet', width: 768, height: 1024, label: 'Tablet (768x1024)' },
    { name: 'mobile', width: 375, height: 812, label: 'Mobile (375x812)' },
  ];

  const results: { viewport: string; score: string; analysis: string; screenshot: string }[] = [];

  for (const vp of viewports) {
    console.log(`📸 Capturing ${vp.label}...`);
    const screenshotPath = await captureScreenshot(url, vp.name, { width: vp.width, height: vp.height });
    console.log(`🧠 Analyzing with AI vision...\n`);

    const analysis = await analyzeScreenshot(
      screenshotPath,
      `This is a ${vp.label} viewport of a cal.com booking page. Focus on whether the booking flow is usable at this screen size.`
    );

    // Extract score from analysis
    const scoreMatch = analysis.match(/(\d+)\/10|(\d+) out of 10/i);
    const score = scoreMatch ? `${scoreMatch[1] || scoreMatch[2]}/10` : 'N/A';

    console.log(`--- ${vp.label} ---`);
    console.log(analysis);
    console.log();

    results.push({
      viewport: vp.label,
      score,
      analysis,
      screenshot: screenshotPath
    });

    // Small delay to avoid rate limits
    await new Promise(r => setTimeout(r, 2000));
  }

  // Generate report
  const report = `# AI Visual Regression Report

**URL Tested:** ${url}  
**Date:** ${new Date().toISOString().split('T')[0]}  
**Tool:** Groq Vision (meta-llama/llama-4-scout-17b-16e-instruct)

---

## Summary

| Viewport | Score | Screenshot |
|---|---|---|
${results.map(r => `| ${r.viewport} | ${r.score} | visual-regression/${r.viewport.split(' ')[0].toLowerCase()}.png |`).join('\n')}

---

## Detailed Analysis

${results.map(r => `
### ${r.viewport}

${r.analysis}

---
`).join('\n')}

*Generated by AI-Native QA Toolkit — Visual Regression Module*
`;

  const reportPath = path.join(process.cwd(), 'visual-regression-report.md');
  fs.writeFileSync(reportPath, report);

  console.log('\n📄 Report saved to: visual-regression-report.md');
  console.log('📸 Screenshots saved to: visual-regression/');
}

const url = process.argv[2] || 'https://cal.com/bailey/chat';
compareViewports(url).catch(console.error);